### ISSUE TITLE
Class goals

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/developers-july-30-2015#1]
Please tell us one thing you would like to learn in today's class!

**Comment by githubstudent** [comment]
I want to learn how to create a pull request!

**Comment by wgannon-sjrwmd** [comment]
All this and more ?!?!?!!?

**Comment by RageAgainstTheVM** [comment]
Connection to Jenkins (tomorrow?)

**Comment by charliewang92** [comment]
rebase reset fork

**Comment by owena** [comment]
I would like to learn pull and push

**Comment by ntend** [comment]
Squashing commits (maybe tommorow?)

**Comment by ghost** [comment]
Some info about GitHub workflow with Xcode.

**Comment by rakshassa** [comment]
How to see parallel files and merge changes.

**Comment by bkerrigan** [comment]
Best practices for rebase vs merge

**Comment by jpallepo** [comment]
adding a comment

**Comment by kirillrudenko** [comment]
I want to understand git better

**Comment by DeyAbhishek** [comment]
Everything to be perfectly comfortable using Git on daily basis

**Comment by CIS-clovertu** [comment]
Push, pull, and merge.

**Comment by pmas1998** [comment]
What is the benefit of GitHub?

**Comment by JeffreyRRoss** [comment]
how to undo actions like commits and pushes

**Comment by mzjliu** [comment]
git reset hard force

**Comment by ALShum** [comment]
I want to learn about different branches.  Also how to not make my computer explode.

**Comment by chrisbSH** [comment]
commet

**Comment by blinblin** [comment]
how to use tags

**Comment by russell-n** [comment]
I second squashing

**Comment by swhitmire** [comment]
How git manages push/pull requests

**Comment by aaiken1** [comment]
How to share code with my co-authors like a real programmer!

**Comment by skempins** [comment]
How to work with GitHub, in general.

**Comment by ghost** [comment]
Work flow from dev to prod or dev to central repository to production?

**Comment by mothur-westcott** [comment]
How to resolve pull push issues that get stuck in a bad state?

**Comment by cnishith** [comment]
Learn the right way to branch and manage development on a project.

**Comment by sh-mikem** [comment]
+1 for using tags

**Comment by ghost** [comment]
I want to learn  installation to configuration

**Comment by cchay** [comment]
finally found it.

**Comment by ankitsharma13** [comment]
everything about git

**Comment by wsunsjr** [comment]
I like the CAT

**Comment by berrye** [comment]
how to use branches

**Comment by ijlyttle** [comment]
What I should actually be doing, instead of what I am doing

**Comment by mothur-westcott** [comment]
All of the above on others comments, :)

**Comment by tevtek1** [comment]
pull requests and merging branches

**Comment by JeffreyRRoss** [comment]
What's the diff between GitLab and GitHub

**Comment by ebuceci** [comment]
Is there a way to git merge in the github web interface?

**Comment by rgarapat** [comment]
Learn how to use github.

**Comment by cjlems** [comment]
moving code to/from GitLab/GitHub

**Comment by Estherbunny** [comment]
merge conflicts advice

**Comment by johnboy55** [comment]
when to rebase

**Comment by ghost** [comment]
I would like to know if this class focus on github or I can learn concepts that I can use any hosted git?

**Comment by ghost** [comment]
git flow for visual studio and gitflow for Wordpress/Magento.

**Comment by ghost** [comment]
version control database?

**Comment by tallus** [comment]
I want to learn how to cherrypick pull requests

**Comment by dcondol** [comment]
Making a comment

**Comment by larissasimplyhired** [comment]
+1 rebasing

**Comment by jonbjohns** [comment]
rebasing

**Comment by azorko** [comment]
would love to learn the advanced features of git :)

**Comment by bryanjenningz** [comment]
rebasing

**Comment by divyakarthikeyan89** [comment]
merging branches

**Comment by tomatoplant** [comment]
rebasing

**Comment by ametla** [comment]
I want to learn how to integrate with OnTime.

**Comment by sdrigger** [comment]
Please add me

**Comment by SunainaVijay** [comment]
Merging!

**Comment by cathleen** [comment]
good morning!

**Comment by mlkebedeUSCIS** [comment]
test

**Comment by elaine0217** [comment]
test

**Comment by patrickmckenna** [comment]
@mlkebede @elaine0217 You're good to go!

**Comment by delaneyparker** [comment]
thanks!

**Comment by atcunningham** [comment]
working on it.

**Comment by moulouddz** [comment]
learning Git hub

**Comment by ankitatiku** [comment]
Learning

**Comment by newlatha** [comment]
I have started now

**Comment by itufail** [comment]
working on it

**Comment by edean-sjrwmd** [comment]
Checking to see if I'm added - thanks.  (Ellen Dean - user:  deanme18)

**Comment by jihuncho** [comment]
test

**Comment by huyingleo** [comment]
thanks
