### ISSUE TITLE
I want to learn how to integrate with OnTime.

### ISSUE THREAD

**Issue by ametla** [githubteacher/developers-july-30-2015#11]
I want to learn how to integrate with OnTime.

**Comment by patrickmckenna** [comment]
@ametla Unfortunately, we don't have time to cover 3rd party tool integrations in this class. That said, it looks like OnTime [already has GitHub integration](http://blog.axosoft.com/2011/11/07/ontime-11-1-subitems-github-and-drag-and-drop/) (scroll down to the section called _GitHub Integration_).
