### ISSUE TITLE
What is common practice for using issue numbers and commits?

### ISSUE THREAD

**Issue by mothur-westcott** [githubteacher/developers-july-30-2015#122]
For example currently I add #IssueNumber to all commits and merges, and also comment with the final commit tag when I close the issue.  What would be the best practice?

**Comment by patrickmckenna** [comment]
@mothur-westcott A bit unclear on the question. Were you asking when and how often one should cross-reference an Issue in a given Pull Request? If so, the usual practice is to do so just once, in the original post of the Pull Request.

Does that clarify things?
