### ISSUE TITLE
Changing file in online editor; Conversation does not reflect the updated file/commit.

### ISSUE THREAD

**Issue by ebuceci** [githubteacher/developers-july-30-2015#141]
is this a bug?

**Comment by ebuceci** [comment]
Sample: https://github.com/githubteacher/developers-july-30-2015/pull/111

**Comment by patrickmckenna** [comment]
The linked Pull Request does in fact reflect both commits you made. You can see them by clicking on the _Commits_ tab in the Pull Request itself:

<img width="464" alt="screen shot 2015-07-30 at 10 35 01 am" src="https://cloud.githubusercontent.com/assets/3589536/8990411/f80a6542-36a6-11e5-8a3b-9dca6b0bd4cc.png">
