### ISSUE TITLE
How do I find everywhere that I am tagged?

### ISSUE THREAD

**Issue by rakshassa** [githubteacher/developers-july-30-2015#143]
If someone tags me in a pull request, issue, or comment.... how can I find all of those places so I can respond?

**Comment by patrickmckenna** [comment]
@rakshassa Hopefully Cynthia just answered your question aloud?

**Comment by patrickmckenna** [comment]
You can also add `mentions:rakshassa` to any GitHub search field, e.g.

<img width="417" alt="screen shot 2015-07-30 at 10 44 23 am" src="https://cloud.githubusercontent.com/assets/3589536/8990562/091f112e-36a8-11e5-9c44-fc03536d7f16.png">

You can do much more granular searching with [Advanced Search](https://github.com/search/advanced).
