### ISSUE TITLE
Git add

### ISSUE THREAD

**Issue by dcondol** [githubteacher/developers-july-30-2015#190]
Is git add -A the same as git add . ?

**Comment by patrickmckenna** [comment]
@dcondol They are. (Double checking that I'm not forgetting some subtlety.)

**Comment by patrickmckenna** [comment]
@dcondol Sorry, bone-headed moment from me. `git add .` stages any changed or new files in the current directory and its subdirectories. If you run the command from within one of those subdirectories, it will not stage any new/changed files in the parent folder(s).

`git add -A` stages all new and changed files, regardless of where you run the command.
