### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by pmas1998** [githubteacher/developers-july-30-2015#199]
I think you moved too quickly through the commands.

**Comment by githubteacher** [comment]
@pmas1998 thank you for your feedback. Are you attending tomorrow? We will go back through the commands tomorrow so hopefully it will be easier with the review.

**Comment by pmas1998** [comment]
Yes I’ll be attending tomorrow. Thanks.

Peter T. Masters
Senior Application Developer
Office of Information Technology
St. Johns River Water Management District
P.O. Box 1429, Palatka, Florida 32178-1429
Office: (386) 329-4493
Website: floridaswater.comhttp://floridaswater.com/
