### ISSUE TITLE
Branch problem

### ISSUE THREAD

**Issue by cchay** [githubteacher/developers-july-30-2015#202]
I added a branch locally, and pushed with no errors.  status shows working directory clean.  But it doesn't show up in github.  Why not?
@githubteacher 
@patrickmckenna

**Comment by cchay** [comment]
the branch is called "cchay_test".

**Comment by patrickmckenna** [comment]
@cchay Are you still running in to trouble? I see a number of branches created by you:

<img width="353" alt="screen shot 2015-07-31 at 10 19 30 am" src="https://cloud.githubusercontent.com/assets/3589536/9012957/b679dcda-376d-11e5-8348-305a0ca4d34a.png">
