### ISSUE TITLE
Add bio for rakshassa

### ISSUE THREAD

**Issue by rakshassa** [githubteacher/developers-july-30-2015#34]
My name is Elijah Hall
My github account name is rakshassa

### Please add my bio

- [ ] Name: Elijah Hall
- [ ] Location: Colorado, USA
- [ ] Occupation: Security Software Engineer
- [ ] Hobbies: Video games, rock climbing, volleyball, board games

@githubstudent Nice bio
@cjlems You need a better bio, bro

**Comment by cjlems** [comment]
Unmerge please.

:ramen:
