### ISSUE TITLE
How to integrate with Leankit?

### ISSUE THREAD

**Issue by cchay** [githubteacher/developers-july-30-2015#38]
Possible?

**Comment by patrickmckenna** [comment]
@cchay Unfortunately these intro classes aren't long enough to really cover 3rd party integrations.

Evidently others have [created LeanKit integrations](https://zapier.com/zapbook/github/leankit/) though.

**Comment by cchay** [comment]
I understand.  But is it possible?

**Comment by patrickmckenna** [comment]
@cchay I believe so, please see the link above.

**Comment by cchay** [comment]
Perfect!  Thanks!
