### ISSUE TITLE
Branch will not create

### ISSUE THREAD

**Issue by atcunningham** [githubteacher/developers-july-30-2015#72]
Had some technical difficulties with sound, so now catching up. Typed into master branch drop down to create new branch, but not creating.

**Comment by patrickmckenna** [comment]
@atcunningham please leave a comment on #1.

**Comment by patrickmckenna** [comment]
@atcunningham It looks like you haven't commented on #1 yet, so I'm manually adding you.

**Comment by atcunningham** [comment]
I’ll do that. We’re having issues here so getting constantly interrupted.

Thanks,
Rhonda

Aarhonda Cunningham
Database Administrator
Serco-NA
(816)251-2356

**Comment by patrickmckenna** [comment]
> We’re having issues here

@atcunningham What exactly are the issues? Are they still affecting you?
